### PR TITLE
Exit club modal when the escape key is pressed

### PR DESCRIPTION
**Pull request by sigmachirality**

### CODE REVIEW

**Comment by ccabo1** [comment]
I think we need to remove the event listener when the modal is closed, else we are building up a lot of them

**Comment by ccabo1** [comment]
Maybe take a look at what we do here: https://github.com/pennlabs/pennbasics/blob/master/src/frontend/components/shared/Modal.js

**Comment by LeoNero** [comment]
I don't think doing things directly on `document` is recommended. But there's been some time since I used React for the last time, so I'm not entirely sure :P

**Comment by sigmachirality** [comment]
rip modal

**Pull request closed without merging**
