### PR TITLE
Migrate to Next.js Dynamic Routing

### PR DESCRIPTION
**Pull request by sigmachirality**
- [x] Remove next-routes package
- [x] Rewrite site to use built in dynamic routing
- [x] Make the website load again
- [x] Fix client/server webpack code split issues
- [x] Test invite new member functionality

### CODE REVIEW

**Comment by sigmachirality** [comment]
I think this is good to go, so now I'm waiting on a review here

**Comment by ezwang** [comment]
Note that these changes do break the maintenance mode page that used to be set in `server/index.js`. Might want to make a task to restore this functionality in a later merge request, if we still want it!

**Comment by sigmachirality** [comment]
@ezwang maybe we can add a smaller index.js and a new package.json command just to host the maintenance server

**Comment by ezwang** [comment]
Also, does this resolve/is related to #56?

**Comment by cacabo** [comment]
So what's the status of this PR now?

**Comment by ezwang** [comment]
I think that this PR should be ready to merge. @cacabo the style issues you mentioned in #65 came from this PR, so if you merge this and then that the fixes should all be applied.

**Pull request merged**
